name: shared_data
description: Shared data models and entities for the coffee shop project.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1    
